apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: aiplatform
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: control-plane
        static_configs:
          - targets: ['host.docker.internal:8080']

      - job_name: operator
        static_configs:
          - targets: ['host.docker.internal:8082']

      - job_name: triton
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: [aiplatform]
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: triton
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: $1:8002
